// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kguwxngsoylukflxovmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtndXd4bmdzb3lsdWtmbHhvdm13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMDEwNTYsImV4cCI6MjA1NDc3NzA1Nn0.tsYxcavq3jP_Tg2L9CIqrwg3E4Dxa_ud9JzujqHngtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
